"""Alter User Ativo

Revision ID: 2481b8009160
Revises: 81abc198ed5e
Create Date: 2022-03-12 19:42:32.441695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2481b8009160'
down_revision = '81abc198ed5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ativo', sa.Boolean(), nullable=True))
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'ativo')
    # ### end Alembic commands ###
