"""Identity Basic3

Revision ID: 81abc198ed5e
Revises: 7ebd4dbd5a1b
Create Date: 2022-03-09 18:34:59.448622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81abc198ed5e'
down_revision = '7ebd4dbd5a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
