"""Identity Basic

Revision ID: efad1699c9ee
Revises: 31e7abe5fef3
Create Date: 2022-03-09 17:32:56.389148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efad1699c9ee'
down_revision = '31e7abe5fef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
